### ISSUE TITLE
About the YMJA dataset

### ISSUE THREAD

**Issue by drwangusm** [cyrilyared/Primal-Dual-Block-Frank-Wolfe-Reproduction#1]
Hello, I can't find your email or other contact info, so I have a question for you here. Where can I find a description of the YMJA dataset for the inter-rel-net project ? I've searched for a long time and couldn't find it. Thank [you.](https://github.com/mauriciolp/inter-rel-net/compare/master...IMVDsports:inter-rel-net:master)

**Comment by cyrilyared** [comment]
Hi, the YMJA dataset can be found here: https://github.com/IMVDsports/inter-rel-net/tree/master/data/YMJA
